version: '3'

services:
  bind9:
    container_name: dns-serveur
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Paris
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    volumes:
      - ./config:/etc/bind
    networks:
      network:
        ipv4_address: 10.5.0.5
    restart: unless-stopped

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1